### ISSUE TITLE
Lake problem broken hyperlinks

### ISSUE THREAD

**Issue by ahamilton144** [reedgroup/reedgroup.github.io#1]
In the lake problem training ipynb, the table contains broken hyperlinks to two python files. 
PS I know that is just placeholder material for now, I mostly just wanted to test/demonstrate how to use GH Issues for collaboration & bug reporting.

**Comment by davidfgold** [comment]
@ahamilton144 good thinking! This works well, I got an email notification and it's a nice way to keep this organized.
